### PR TITLE
Support mysql materialized views

### PR DESCRIPTION
**Pull request by lonnylot**
MySQL doesn't use 'materialized'. However, you can create a view that forces temptable, which is similar.

### CODE REVIEW

**Comment by staudenmeir** [comment]
Hi @lonnylot,
Thanks, I'll take a look.

**Comment by staudenmeir** [comment]
Please allow edit access for maintainers on this PR.

**Comment by lonnylot** [comment]
Any idea how I do that?

**Comment by staudenmeir** [comment]
There's a checkbox on the right (on Desktop):

Bildschirmfoto 2024-10-21 um 09 17 07

**Comment by lonnylot** [comment]
Screenshot 2024-10-21 at 7 17 11 AM

Possible only you have that? Feel free to enable it.

**Comment by staudenmeir** [comment]
Weird. Only PR authors have that option. My screenshot was from one of my own PRs.

I'll merge your PR and refactor it afterwards.

**Comment by lonnylot** [comment]
¯\_(ツ)_/¯ either way thank you 🙏

**Comment by staudenmeir** [comment]
I rewrote your PR so that there's now an `algorithm` parameter:
https://github.com/staudenmeir/laravel-migration-views?tab=readme-ov-file#view-processing-algorithm

IMO, `TEMPTABLE`  views aren't similar enough to PostgreSQL's materialized views and so I don't want to use `createMaterializedView()` for that. MySQL and/or MariaDB could also support "real" materialized views at some point.

**Pull request merged**
